name: Build
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install docker
        run: >
          sudo apt update -y -qqq ; 
          sudo apt install -y -qqq bash wget ca-certificates curl git ; 
          sudo ln -svf bash /bin/sh ; 
          sudo bash docker/.pre ; 
          sudo apt upgrade -fy -qqq;
          sudo bash docker/install_docker.sh;

      - name: Build keepalived ub2204
        run: |
          sudo bash run-build-ub2204.sh
          sudo systemctl stop docker.socket docker.service containerd.service
          sudo rm -fr /var/lib/docker/*
      - name: Upload keepalived ub2204
        run: |
          _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
          _keepalived_ver="$(sudo ls -1 /home/.tmp.keepalived/keepalived-* | sed -e 's|.*keepalived-||g' -e 's|-.*||g' | tail -n1)"
          sudo ls -1 /home/.tmp.keepalived/keepalived-* | sudo xargs --no-run-if-empty -I '{}' sudo bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_keepalived_ver}" -k "${{ secrets.GITHUB_TOKEN }}"

      #- name: Build keepalived el8
      #  run: |
      #    sudo bash run-build-el8.sh
      #    sudo systemctl stop docker.socket docker.service containerd.service
      #    sudo rm -fr /var/lib/docker/*
      #- name: Upload keepalived el8
      #  run: |
      #    _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
      #    _keepalived_ver="$(sudo ls -1 /home/.tmp.keepalived/keepalived-* | sed -e 's|.*keepalived-||g' -e 's|-.*||g' | tail -n1)"
      #    sudo ls -1 /home/.tmp.keepalived/keepalived-* | sudo xargs --no-run-if-empty -I '{}' sudo bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_keepalived_ver}" -k "${{ secrets.GITHUB_TOKEN }}"

      - name: Build keepalived ub2004
        run: |
          sudo bash run-build-ub2004.sh
          sudo systemctl stop docker.socket docker.service containerd.service
          sudo rm -fr /var/lib/docker/*
      - name: Upload keepalived ub2004
        run: |
          _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
          _keepalived_ver="$(sudo ls -1 /home/.tmp.keepalived/keepalived-* | sed -e 's|.*keepalived-||g' -e 's|-.*||g' | tail -n1)"
          sudo ls -1 /home/.tmp.keepalived/keepalived-* | sudo xargs --no-run-if-empty -I '{}' sudo bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_keepalived_ver}" -k "${{ secrets.GITHUB_TOKEN }}"
