name: Build
on:
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install docker
        run: >
          sudo apt update -y -qqq;
          sudo apt autoremove --purge -y needrestart || true;
          sudo apt install -y bash wget;
          sudo ln -svf bash /bin/sh;
          sudo bash docker/clean-os.sh;
          sudo apt upgrade -y -qqq;
          sudo bash docker/install-docker.sh

      - name: Create output tmp
        run: |
          /bin/rm -fr /tmp/_output.tmp
          mkdir /tmp/_output.tmp

      - name: Build keepalived al9
        run: |
          sudo bash run-build-al9.sh
          sudo systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/* /mnt/docker-data/*

      - name: Build keepalived al8
        run: |
          sudo bash run-build-al8.sh
          sudo systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/* /mnt/docker-data/*

      - name: Build keepalived ub2204
        run: |
          sudo bash run-build-ub2204.sh
          sudo systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/* /mnt/docker-data/*

      - name: Build keepalived ub2004
        run: |
          sudo bash run-build-ub2004.sh
          sudo systemctl stop docker.socket docker.service containerd.service
          sudo /bin/rm -fr /var/lib/docker/* /var/lib/containerd/* /mnt/docker-data/*

      - name: Generate release tag env
        run: |
          echo "_dateutc=$(date -u +%Y-%m-%d-%H%M)" >> $GITHUB_ENV

      - name: Upload files
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env._dateutc }}
          files: /tmp/_output.tmp/*

      - name: Delete old release tag env
        run: |
          sed -e "/^_dateutc=/d" -i $GITHUB_ENV

